---
- name: Mettre a jour le cache apt
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Installer les paquets communs
  ansible.builtin.apt:
    name:
      - curl
      - vim
      - git
      - htop
      - net-tools
      - chrony
    state: present

- name: Configurer le fuseau horaire
  ansible.builtin.timezone:
    name: Europe/Paris

- name: S'assurer que chrony (NTP) est demarre et actif
  ansible.builtin.service:
    name: chrony
    state: started
    enabled: true
