FROM alpine:3.18

RUN apk add --no-cache openssh sudo && \
    ssh-keygen -A && \
    adduser -D -s /bin/ash ansible

RUN sed -i 's/^#PermitRootLogin.*/PermitRootLogin no/' /etc/ssh/sshd_config

EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]
