FROM ubuntu:22.04

RUN apt-get update && apt-get install -y openssh-server sudo && \
    mkdir /var/run/sshd && \
    rm -rf /var/lib/apt/lists/* && \
    useradd -rm -d /home/ansible -s /bin/bash -g root -G sudo -u 1000 ansible

RUN sed -i 's/^#PermitRootLogin.*/PermitRootLogin no/' /etc/ssh/sshd_config

EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]
