# Inventaire Ansible — Shellter
# Auteur : P4 (Jamai Ali) — Séance S2
# Réseau privé Vagrant : 192.168.56.0/24  (voir docs/architecture.md)

[controller]
controller ansible_host=192.168.56.10

[workers]
worker1 ansible_host=192.168.56.11
worker2 ansible_host=192.168.56.12
worker3 ansible_host=192.168.56.13

# Groupe global : toutes les VM du projet
[shellter:children]
controller
workers
